"""Single catalog of API paths. Change URLs here only."""

API_PREFIX = "/api/v1"


class Routes:
    ADMIN_LOGIN = f"{API_PREFIX}/admin/login"
    ADMIN_ME = f"{API_PREFIX}/admin/me"
    ADMIN_USERS = f"{API_PREFIX}/admin/users"
    ADMIN_USER_ACTIVATE = f"{API_PREFIX}/admin/users/{{user_id}}/activate"
    ADMIN_USER_PLAN = f"{API_PREFIX}/admin/users/{{user_id}}/plan"
    ADMIN_USER_REMOVE = f"{API_PREFIX}/admin/users/{{user_id}}/remove"
    ADMIN_USER_RESTORE = f"{API_PREFIX}/admin/users/{{user_id}}/restore"
    ADMIN_NAICS_CATALOG = f"{API_PREFIX}/admin/naics/catalog"
    ADMIN_USER_NAICS = f"{API_PREFIX}/admin/users/{{user_id}}/naics"
    ADMIN_PAYMENTS = f"{API_PREFIX}/admin/payments"
    ADMIN_LEADS = f"{API_PREFIX}/admin/leads"
    ADMIN_LEAD = f"{API_PREFIX}/admin/leads/{{lead_id}}"
    CONTACT = f"{API_PREFIX}/contact"
    ACCESS_REQUESTS = f"{API_PREFIX}/access-requests"
    FREE_SIGNUP = f"{API_PREFIX}/plans/free/signup"
    RAZORPAY_ORDER = f"{API_PREFIX}/payments/razorpay/order"
    RAZORPAY_VERIFY = f"{API_PREFIX}/payments/razorpay/verify"
    AUTH_LOGIN = f"{API_PREFIX}/auth/login"
    AUTH_ME = f"{API_PREFIX}/auth/me"
    AUTH_SET_PASSWORD = f"{API_PREFIX}/auth/set-password"
    AUTH_RESEND_SETUP = f"{API_PREFIX}/auth/resend-setup"
    AUTH_PROVISIONING_STATUS = f"{API_PREFIX}/auth/provisioning-status"
    RADAR_RUN = f"{API_PREFIX}/radar/run"
    RADAR_RESULTS = f"{API_PREFIX}/radar/results"
    RADAR_STATUS = f"{API_PREFIX}/radar/status"
    RADAR_RUNS = f"{API_PREFIX}/radar/runs"
    ADMIN_USER_RADAR_RUNS = f"{API_PREFIX}/admin/users/{{user_id}}/radar-runs"
    WORKSPACE_TEAM = f"{API_PREFIX}/workspace/team"
    WORKSPACE_TEAM_INVITE = f"{API_PREFIX}/workspace/team/invite"
    WORKSPACE_TEAM_MEMBER = f"{API_PREFIX}/workspace/team/{{member_id}}"

    # OP frontend read API. Paths match OP's src/services/*.ts.
    OP_OPPORTUNITIES = f"{API_PREFIX}/opportunities"
    OP_OPPORTUNITY_COMPANIES = f"{API_PREFIX}/opportunities/companies"
    OP_COMPANY_HIRING_SIGNAL = f"{API_PREFIX}/opportunities/companies/{{company_id}}/hiring-signal"
    OP_OPPORTUNITY = f"{API_PREFIX}/opportunities/{{opportunity_id}}"
    OP_OPPORTUNITY_OPEN = f"{API_PREFIX}/opportunities/{{opportunity_id}}/open"
    OP_OPPORTUNITY_ACTIVITY = f"{API_PREFIX}/opportunities/{{opportunity_id}}/activity"
    OP_OPPORTUNITY_OUTREACH = f"{API_PREFIX}/opportunities/{{opportunity_id}}/outreach"
    OP_OPPORTUNITY_ASSIGNMENTS = f"{API_PREFIX}/opportunities/{{opportunity_id}}/assignments"
    OP_OPPORTUNITY_ASSIGN = f"{API_PREFIX}/opportunities/{{opportunity_id}}/assign"
    OP_OPPORTUNITY_SAVED = f"{API_PREFIX}/opportunities/{{opportunity_id}}/saved"
    OP_OPPORTUNITY_NOTES = f"{API_PREFIX}/opportunities/{{opportunity_id}}/notes"
    OP_OPPORTUNITY_FOLLOW_UP = f"{API_PREFIX}/opportunities/{{opportunity_id}}/follow-up"
    OP_VENDORS = f"{API_PREFIX}/vendors"
    OP_VENDOR = f"{API_PREFIX}/vendors/{{vendor_id}}"
    OP_DASHBOARD_METRICS = f"{API_PREFIX}/dashboard/metrics"
    OP_DASHBOARD_OVERVIEW = f"{API_PREFIX}/dashboard/overview"
    OP_DASHBOARD_PIPELINE = f"{API_PREFIX}/dashboard/pipeline"
    OP_DASHBOARD_ATTENTION = f"{API_PREFIX}/dashboard/needs-attention"
    OP_DASHBOARD_DEADLINES = f"{API_PREFIX}/dashboard/deadlines"
    OP_ACTIVITY = f"{API_PREFIX}/activity"
    OP_ASSIGNMENTS_ME = f"{API_PREFIX}/assignments/me"
    OP_TEAM_OWNERSHIP = f"{API_PREFIX}/team/ownership"
    OP_NOTIFICATIONS = f"{API_PREFIX}/notifications"
    OP_NOTIFICATION_READ = f"{API_PREFIX}/notifications/{{notification_id}}/read"
    OP_NOTIFICATIONS_READ_ALL = f"{API_PREFIX}/notifications/read-all"
    OP_SAVED_VIEWS = f"{API_PREFIX}/saved-views"
    OP_SAVED_VIEW = f"{API_PREFIX}/saved-views/{{view_id}}"
    OP_SEARCH = f"{API_PREFIX}/search"
    OP_OUTREACH = f"{API_PREFIX}/outreach"
